/*  Auth constants   */
export const TOKEN_VERIFIED = 'TOKEN_VERIFIED';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const DROP_DOWN_VALUES = 'DROP_DOWN_VALUES';
export const MY_PROFILE = 'MY_PROFILE';
export const GET_LIST_INSPECTORS = 'GET_LIST_INSPECTORS';
export const LIST_OF_ALL_ENQUIRIES = 'LIST_OF_ALL_ENQUIRIES';
export const LIST_OF_ALL_JOB_ORDERS = 'LIST_OF_ALL_JOB_ORDERS';
export const ACCCEPTED_REQUEST = 'ACCCEPTED_REQUEST';
export const DECLINED_RESPONSE = 'DECLINED_RESPONSE';